kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: node14
    commands:
      - npm install
      - npm run build
      - start-server-and-test start http://localhost:3000 cypress:ci
  - name: update-status-to-github
    image: codehimanshu/gitdrone:1.7
    environment:
      drone_access_token:
        from_secret: drone_access_token
      github_installation_id:
        from_secret: github_installation_id
      github_app_id: 1718965
      private_key:
        from_secret: private_key
    when:
      status: [failure, success]
      event: pull_request

trigger:
  event:
    - pull_request
