kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: cypress/base
    commands:
      - npm install
      - npm run build
      - npm run start:ci
  

trigger:
  event:
    - pull_request
