import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import path from "path";
import Layout from "../components/Layout";
import { postFilePaths, POSTS_PATH } from "../utils/mdxUtils";
import Head from "next/head";

type Posts = {
  content: string;
  data: { [key: string]: any };
  filePath: string;
};

export default function Index({ posts }: { posts: Posts[] }) {
  return (
    <>
      <Head>
        <title>Blog homepage</title>
      </Head>
      <Layout>
        <main
          style={{
            margin: "0 auto",
            width: "90vw",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <h1>Home Page</h1>
          <p>
            Click the link below to navigate to a page generated by{" "}
            <code>next-mdx-remote</code>.
          </p>
          <ul>
            {posts.map((post) => (
              <li key={post.filePath}>
                <Link
                  as={`/posts/${post.filePath.replace(/\.mdx?$/, "")}`}
                  href={`/posts/[slug]`}
                >
                  <a>
                    <h2>{post.data.title}</h2>
                    <p>{post.data.description}</p>
                    Read more
                  </a>
                </Link>
              </li>
            ))}
          </ul>
        </main>
      </Layout>
    </>
  );
}

export function getStaticProps() {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
    const { content, data } = matter(source);

    return {
      content,
      data,
      filePath: filePath.replace(".mdx", ""),
    };
  });

  return { props: { posts } };
}
